/** Fase 6B — Channel Hardening defaults (CH1–CH12). */

export const EVOLUTION_TIMEOUT_SEND_MS_DEFAULT = 15_000;
export const EVOLUTION_TIMEOUT_CONNECT_MS_DEFAULT = 20_000;
export const EVOLUTION_TIMEOUT_DEFAULT_MS_DEFAULT = 10_000;

export const EVOLUTION_RETRY_MAX_DEFAULT = 2;
export const EVOLUTION_RETRY_BASE_MS_DEFAULT = 200;
export const EVOLUTION_RETRY_MAX_DELAY_MS_DEFAULT = 2_000;
export const EVOLUTION_RETRY_JITTER_MS_DEFAULT = 200;
export const EVOLUTION_RATE_LIMIT_WAIT_MAX_MS_DEFAULT = 5_000;

export const EVOLUTION_CB_FAILURE_THRESHOLD_DEFAULT = 5;
export const EVOLUTION_CB_SUCCESS_THRESHOLD_DEFAULT = 2;
export const EVOLUTION_CB_OPEN_MS_DEFAULT = 30_000;
export const EVOLUTION_CB_HALF_OPEN_MAX_CALLS_DEFAULT = 1;

/** Reconnect / connect cooldown per instance (CH / P6B-9). */
export const EVOLUTION_CONNECT_COOLDOWN_MS_DEFAULT = 10_000;

export const WEBHOOK_SLOW_MS_DEFAULT = 2_000;
export const WEBHOOK_MAX_INFLIGHT_DEFAULT = 50;

export const OPS_RECONCILE_TAKE_DEFAULT = 100;

export const EVOLUTION_ERROR_CLASS = {
  TIMEOUT: 'TIMEOUT',
  NETWORK: 'NETWORK',
  RATE_LIMIT: 'RATE_LIMIT',
  PROVIDER_5XX: 'PROVIDER_5XX',
  PROVIDER_4XX: 'PROVIDER_4XX',
  STUB_FORBIDDEN: 'STUB_FORBIDDEN',
  CIRCUIT_OPEN: 'CIRCUIT_OPEN',
  CONNECT_COOLDOWN: 'CONNECT_COOLDOWN',
  UNCERTAIN_TIMEOUT: 'UNCERTAIN_TIMEOUT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type EvolutionErrorClass =
  (typeof EVOLUTION_ERROR_CLASS)[keyof typeof EVOLUTION_ERROR_CLASS];

export type CircuitState = 'CLOSED' | 'OPEN' | 'HALF_OPEN';
